import type { Profile } from '@/lib/types'

// Local seed data so the app is fully browsable in demo mode (no Supabase yet).
// Mirrors the shape of the `profiles` table in supabase/schema.sql.
export const DEMO_PROFILES: Profile[] = [
  {
    id: 'demo-dev-1',
    user_id: null,
    user_type: 'developer',
    handle: 'solslinger',
    display_name: 'Ava “solslinger” Reyes',
    bio: 'Anchor + TypeScript dev. I ship Solana programs and clean React front-ends. Ex-DeFi, now helping newcomers launch their first token responsibly.',
    avatar_url: null,
    wallet_address: '7xKXtg2CW3s1e9wY1i6mR3n4pC8fQ2vH5uJ9bN0aZ1d',
    skills: ['dev', 'design', 'product'],
    portfolio_links: [
      { label: 'anchor-escrow (repo)', url: 'https://github.com/example/anchor-escrow' },
      { label: 'Case study: NFT mint', url: 'https://example.com/case-study' },
    ],
    socials: { x: 'solslinger', github: 'solslinger', website: 'https://ava.dev' },
    showcase: [
      { id: 's1', title: 'On-chain vesting UI', description: 'Streaming vesting dashboard', url: 'https://example.com/vesting' },
      { id: 's2', title: 'Wallet onboarding kit', description: 'Drop-in connect flow', url: 'https://example.com/kit' },
    ],
    created_at: '2025-01-10T10:00:00Z',
    updated_at: '2025-01-10T10:00:00Z',
  },
  {
    id: 'demo-dev-2',
    user_id: null,
    user_type: 'developer',
    handle: 'pixelmancer',
    display_name: 'Kojo Mensah',
    bio: 'Motion designer & brand builder for crypto projects. Memecoin identities, explainer animations, and landing pages that convert.',
    avatar_url: null,
    wallet_address: 'D3vB9pQ1r7sN2mK4tL6uW8xY0zA1cE3fG5hJ7kM9nP2',
    skills: ['art', 'design', 'marketing', 'video'],
    portfolio_links: [{ label: 'Dribbble', url: 'https://dribbble.com/example' }],
    socials: { x: 'pixelmancer', website: 'https://kojo.studio' },
    showcase: [
      { id: 's1', title: '$DOGGO rebrand', description: 'Full identity + site', url: 'https://example.com/doggo' },
    ],
    created_at: '2025-01-12T10:00:00Z',
    updated_at: '2025-01-12T10:00:00Z',
  },
  {
    id: 'demo-dev-3',
    user_id: null,
    user_type: 'developer',
    handle: 'chainsmith',
    display_name: 'Lena Ortiz',
    bio: 'Rust engineer focused on audits and safe program design. I review buyback/burn mechanisms and treasury flows before they touch mainnet.',
    avatar_url: null,
    wallet_address: 'A1bC2dE3fG4hJ5kL6mN7pQ8rS9tU0vW1xY2zZ3aB4cD',
    skills: ['dev', 'research', 'ops'],
    portfolio_links: [{ label: 'Audit notes', url: 'https://example.com/audits' }],
    socials: { github: 'chainsmith', x: 'chainsmith' },
    showcase: [
      { id: 's1', title: 'Treasury guardrails', description: 'PDA-gated spend limits', url: 'https://example.com/guardrails' },
    ],
    created_at: '2025-01-14T10:00:00Z',
    updated_at: '2025-01-14T10:00:00Z',
  },
  {
    id: 'demo-onb-1',
    user_id: null,
    user_type: 'onboardee',
    handle: 'newcoiner',
    display_name: 'Sam Whitfield',
    bio: 'Just got my first Phantom wallet set up. Learning by doing — looking for a dev to help me launch a small community coin the right way.',
    avatar_url: null,
    wallet_address: 'F5gH6jK7lM8nP9qR0sT1uV2wX3yZ4aB5cD6eF7gH8jK',
    skills: ['community', 'marketing'],
    portfolio_links: [],
    socials: { x: 'newcoiner' },
    showcase: [],
    created_at: '2025-01-16T10:00:00Z',
    updated_at: '2025-01-16T10:00:00Z',
  },
  {
    id: 'demo-onb-2',
    user_id: null,
    user_type: 'onboardee',
    handle: 'artby_mira',
    display_name: 'Mira Kovač',
    bio: 'Illustrator moving into web3. I can make art for your project while I learn the tech side. Teach me, and I’ll draw your mascot.',
    avatar_url: null,
    wallet_address: 'K7lM8nP9qR0sT1uV2wX3yZ4aB5cD6eF7gH8jK9lM0nP',
    skills: ['art', 'design'],
    portfolio_links: [{ label: 'Portfolio', url: 'https://example.com/mira' }],
    socials: { x: 'artby_mira', website: 'https://mira.art' },
    showcase: [
      { id: 's1', title: 'Mascot sketches', description: 'Character concepts', url: 'https://example.com/sketches' },
    ],
    created_at: '2025-01-18T10:00:00Z',
    updated_at: '2025-01-18T10:00:00Z',
  },
  {
    id: 'demo-onb-3',
    user_id: null,
    user_type: 'onboardee',
    handle: 'growthguy',
    display_name: 'Deshawn Carter',
    bio: 'Growth marketer from web2. New to Solana but I know how to build communities. Want to learn tokenomics and pair with a builder.',
    avatar_url: null,
    wallet_address: 'M0nP1qR2sT3uV4wX5yZ6aB7cD8eF9gH0jK1lM2nP3qR',
    skills: ['marketing', 'community', 'writing'],
    portfolio_links: [],
    socials: { x: 'growthguy', telegram: 'growthguy' },
    showcase: [],
    created_at: '2025-01-20T10:00:00Z',
    updated_at: '2025-01-20T10:00:00Z',
  },
]
